self.addEventListener('install', event => {
    console.info(`[ServiceWorker] ${event.type}!`);
});

const regexReviewsPage = /\/reviews\/([0-9]+)$/;

self.addEventListener('fetch', event => {
    const [, page] = event.request.url.toString().match(regexReviewsPage) || [];
    if (page) {
        event.respondWith(
            fetch(event.request).catch(err => {
                console.warn(`Error fetching reviews/${page}:`, err);
                const body = JSON.stringify(reviews[page]);
                return new Response(body, {
                    status: 200,
                    statusText: 'OK',
                    headers: { 'Content-Type': 'application/json' }
                });
            })
        );
    }
});

const reviews = [
    {
        reviews: [
            {
                country: 'US',
                reviewId: 'R1SQ32067PGIK5',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'Nice rattle sound',
                content: 'Just as cute as it can be!!! Nice rattle sound!!!',
                stars: 5,
                verified: true,
                reviewCreated: 1517961600000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1518038627000
            },
            {
                country: 'US',
                reviewId: 'R3TGD8Y79S18UQ',
                childAsin: 'B01M3S7P22',
                authorId: '',
                title: 'Smaller than I thought.',
                content:
                    'Smaller than I though it was going to be. Also- when I washed it, the fuzz got all over everything else in the washer/dryer.',
                stars: 3,
                verified: true,
                reviewCreated: 1517616000000,
                productImg: '51+gRXywflL',
                productTitle: 'Hudson Baby Sherpa Blanket with Satin Binding, Pink',
                watched: false,
                created: 1517954722000
            },
            {
                country: 'US',
                reviewId: 'RML4KUCLVHE0S',
                childAsin: 'B01M3S7P22',
                authorId: '',
                title: 'Four Stars',
                content: 'Thin but OK',
                stars: 4,
                verified: false,
                reviewCreated: 1517184000000,
                productImg: '51+gRXywflL',
                productTitle: 'Hudson Baby Sherpa Blanket with Satin Binding, Pink',
                watched: false,
                created: 1517430130000
            },
            {
                country: 'US',
                reviewId: 'R167JDRHY8RJTU',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'Five Stars',
                content: 'Absolutely adorable',
                stars: 5,
                verified: true,
                reviewCreated: 1517011200000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1517430006000
            },
            {
                country: 'US',
                reviewId: 'R1V342AML5YST2',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'Five Stars',
                content: 'Very pleased with product',
                stars: 5,
                verified: true,
                reviewCreated: 1516924800000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1517430006000
            },
            {
                country: 'US',
                reviewId: 'R3IXQN3RSCK3FL',
                childAsin: 'B01M3S7P22',
                authorId: '',
                title: 'Three Stars',
                content: "didn't really like the material",
                stars: 3,
                verified: true,
                reviewCreated: 1516924800000,
                productImg: '51+gRXywflL',
                productTitle: 'Hudson Baby Sherpa Blanket with Satin Binding, Pink',
                watched: false,
                changed: 1517693097000,
                created: 1517430130000
            },
            {
                country: 'US',
                reviewId: 'R3L9TJRR1FXFPX',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'When inflated, the ball is an odd egg-shape -- ...',
                content:
                    'When inflated, the ball is an odd egg-shape -- not what I was expecting but it still does the trick!',
                stars: 3,
                verified: true,
                reviewCreated: 1516492800000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R317ZOWHPLTBOV',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'Five Stars',
                content: 'So adorable!',
                stars: 5,
                verified: true,
                reviewCreated: 1516233600000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1517430006000
            },
            {
                country: 'US',
                reviewId: 'R1YZ4TBYNZYJ1Q',
                childAsin: 'B01M3S7P22',
                authorId: '',
                title: 'nice color',
                content: 'So soft, nice color',
                stars: 5,
                verified: true,
                reviewCreated: 1515715200000,
                productImg: '51+gRXywflL',
                productTitle: 'Hudson Baby Sherpa Blanket with Satin Binding, Pink',
                watched: false,
                created: 1517430130000
            },
            {
                country: 'US',
                reviewId: 'RGDDQWGJ67J33',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'SO Cute!!!',
                content: 'I loved it... it is so cute and very good quality!!!',
                stars: 5,
                verified: true,
                reviewCreated: 1515628800000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1517430006000
            },
            {
                country: 'US',
                reviewId: 'R7DO70AUOKCKB',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'Five Stars',
                content: 'Cute',
                stars: 5,
                verified: true,
                reviewCreated: 1515542400000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1517430006000
            },
            {
                country: 'US',
                reviewId: 'R2RRR92UGO1MI7',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'Very cute! Baby shower gift!',
                content: 'Very cute! Baby shower gift!',
                stars: 5,
                verified: true,
                reviewCreated: 1515456000000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1517430006000
            },
            {
                country: 'US',
                reviewId: 'R22FRX31LJ0ODR',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'Adorable',
                content: 'Adorable baby elephant and its little rattle, absolutely loved it!',
                stars: 5,
                verified: true,
                reviewCreated: 1514937600000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1517430006000
            },
            {
                country: 'US',
                reviewId: 'R39TI99M16TX31',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Great value! I use it with my entire body ...',
                content: 'Great value! I use it with my entire body weight and it holds up well.',
                stars: 5,
                verified: true,
                reviewCreated: 1514505600000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'RAGDDT3INBJ5S',
                childAsin: 'B01M3S7P22',
                authorId: '',
                title: 'Three Stars',
                content: 'Blanket is so soft and nice , but very very small .',
                stars: 3,
                verified: true,
                reviewCreated: 1514505600000,
                productImg: '51+gRXywflL',
                productTitle: 'Hudson Baby Sherpa Blanket with Satin Binding, Pink',
                watched: false,
                created: 1517430130000
            },
            {
                country: 'US',
                reviewId: 'R2LRV9JP9MBO0W',
                childAsin: 'B01M3S7P22',
                authorId: '',
                title: 'Very Soft',
                content: 'Very soft. Great blanket!',
                stars: 5,
                verified: true,
                reviewCreated: 1514332800000,
                productImg: '51+gRXywflL',
                productTitle: 'Hudson Baby Sherpa Blanket with Satin Binding, Pink',
                watched: false,
                created: 1517430130000
            },
            {
                country: 'US',
                reviewId: 'R2PX7TAG1ILFD4',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Five Stars',
                content: 'Very easy to inflate. Nice size for exercising. Solid',
                stars: 5,
                verified: true,
                reviewCreated: 1513555200000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R2QFQTH28ZABGZ',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Good Ball for Certain Exercises',
                content:
                    'The ball is just a little bigger than I wanted but I couldn\'t find a 7" ball on the site. But it seems pretty nice. Made of good material and bounces very nicely.',
                stars: 3,
                verified: true,
                reviewCreated: 1513123200000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'RJL4DAYPBL1MI',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'The product was delivered within 2 days and came with ...',
                content:
                    'The product was delivered within 2 days and came with a pump a straw and extra plug and well packaged although i’ve Already lost the extra plug. Made of heavy plastic. Took no time for me to pump up and ready to go. Would buy again from ProBody.',
                stars: 5,
                verified: true,
                reviewCreated: 1512950400000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R4TJN78ZMMCOS',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Would have been nice if it had a self closin hole',
                content:
                    "Been busy and hadn't had a chance but did it now. A little difficult to blow it up and plug it by yourself. Would have been nice if it had a self closin hole. Appreciate the extra stoppers. They wsy it was packed, it appears that some indentations were made on the ball from the stoppers or pump nozzle.",
                stars: 3,
                verified: true,
                reviewCreated: 1512604800000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            }
        ],
        hasMore: true
    },
    {
        reviews: [
            {
                country: 'US',
                reviewId: 'R200Q9ZC09IID3',
                childAsin: 'B01M3S7P22',
                authorId: '',
                title: 'good',
                content: 'fast shipping! good quality',
                stars: 5,
                verified: true,
                reviewCreated: 1512432000000,
                productImg: '51+gRXywflL',
                productTitle: 'Hudson Baby Sherpa Blanket with Satin Binding, Pink',
                watched: false,
                created: 1517430130000
            },
            {
                country: 'US',
                reviewId: 'R3PO3XA664TBWY',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'Four Stars',
                content: 'Good gift',
                stars: 4,
                verified: true,
                reviewCreated: 1512432000000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1517430006000
            },
            {
                country: 'US',
                reviewId: 'R2DYEYYNU5UPY9',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Five Stars',
                content: 'Good quality and service.',
                stars: 5,
                verified: true,
                reviewCreated: 1512086400000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R20GZIWPW5T9K9',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Great fitness ball.',
                content:
                    'I am very happy with my Pilates mini ball. Great quality and also received link showing helpful exercises and stretches. I will definitely order from ProBody in the future!',
                stars: 5,
                verified: true,
                reviewCreated: 1512000000000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R2WQCFEVMCRY69',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Five Stars',
                content:
                    'Great product....it was easy to inflate with the included pump. I would recommend purchasing.',
                stars: 5,
                verified: true,
                reviewCreated: 1511913600000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R23ODB0CJNAUBG',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: '... the exact ball i use at pt and was glad I was able to find one like',
                content: 'This is the exact ball i use at pt and was glad I was able to find one like it',
                stars: 5,
                verified: true,
                reviewCreated: 1511654400000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R3A0NIENQCCLK0',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Easy to inflate and works well',
                content: 'Great price for a great product',
                stars: 5,
                verified: true,
                reviewCreated: 1511654400000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R3VQD1KJN2KQ3Q',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Four Stars',
                content: "I can't give a review at this time since this is a Christmas gift.",
                stars: 4,
                verified: true,
                reviewCreated: 1511654400000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'RQKERSPVOXHOK',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Good product overall',
                content:
                    'Good product overall. The only issue we had was that the pump did not work at all well. It was easier to inflate using a drinking straw.',
                stars: 4,
                verified: true,
                reviewCreated: 1511654400000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'RLOUED1YGDO38',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Highly recommended',
                content:
                    'This exact product was recommended by my physical therapist. It is terrific, easy to pump (I think getting the pump with the ball is smart.), was delivered very quickly. So glad have it.',
                stars: 5,
                verified: true,
                reviewCreated: 1511481600000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R1QGUYWPOCFUPJ',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'it works great however the ball is not round',
                content:
                    'I bought this to help with leg extension exercises post knee replacement. For this purpose, it works great however the ball is not round. It id very oblong and odly shaped.',
                stars: 4,
                verified: true,
                reviewCreated: 1511481600000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R3LWP8ETJUHJHK',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Versatile exercise prop',
                content:
                    'Bought this because we were using something similar in my Barre class at the gym. Love this for doing sit ups/crunches. Reduces risk of back strain and gives a great an workout. Very versatile for numerous exercises.',
                stars: 5,
                verified: true,
                reviewCreated: 1511395200000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R1G21EBXI8589E',
                childAsin: 'B01M3S7P22',
                authorId: '',
                title: 'Five Stars',
                content: 'So incredibly soft.',
                stars: 5,
                verified: true,
                reviewCreated: 1511308800000,
                productImg: '51+gRXywflL',
                productTitle: 'Hudson Baby Sherpa Blanket with Satin Binding, Pink',
                watched: false,
                created: 1517430130000
            },
            {
                country: 'US',
                reviewId: 'R2VK7GMS13OGF7',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Five Stars',
                content: 'Just the right size. Works well between knees.',
                stars: 5,
                verified: true,
                reviewCreated: 1510790400000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R33MDMJP178BVB',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'Five Stars',
                content: 'Looks great. It’s a gift and pictured as exoected',
                stars: 5,
                verified: true,
                reviewCreated: 1510790400000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1517430006000
            },
            {
                country: 'US',
                reviewId: 'R34Z263XZ2A7B2',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'perfect for a cake topper',
                content: 'Used this as a cake topper for a baby shower and it worked out perfectly.',
                stars: 5,
                verified: true,
                reviewCreated: 1510531200000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1517430006000
            },
            {
                country: 'US',
                reviewId: 'R3BOCVORRDQMO1',
                childAsin: 'B01M3S7P22',
                authorId: '',
                title: 'Five Stars',
                content: 'Great price, soft',
                stars: 5,
                verified: true,
                reviewCreated: 1510531200000,
                productImg: '51+gRXywflL',
                productTitle: 'Hudson Baby Sherpa Blanket with Satin Binding, Pink',
                watched: false,
                created: 1517430130000
            },
            {
                country: 'US',
                reviewId: 'R1K9RDXXLYYRW8',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: '... said it would be thank you so much it’s perfect Thank you',
                content:
                    'The Pilates ball is exactly what my instructor said it would be thank you so much it’s perfect Thank you. Todd',
                stars: 5,
                verified: true,
                reviewCreated: 1510358400000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R1EZ69QI4OIQFL',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Worth a try despite the missing star',
                content:
                    "It was easy to inflate. I looks a little oblong rather than perfectly circular. That could be user error, but it also hasn't been a problem for my purposes. No other complaints though I can't say I've put it under much scrutiny.",
                stars: 4,
                verified: true,
                reviewCreated: 1510185600000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R3VVMPGEFUHI9',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'Five Stars',
                content: 'Adorable, perfect looking too. Wish it was a little cheaper.',
                stars: 5,
                verified: true,
                reviewCreated: 1510185600000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1517430006000
            }
        ],
        hasMore: true
    },
    {
        reviews: [
            {
                country: 'US',
                reviewId: 'R3G02WD3YAQTWF',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Five Stars',
                content: "Ordered as a gift for my girlfriend. She hasn't complained about it, so 5 Stars!",
                stars: 5,
                verified: true,
                reviewCreated: 1510099200000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R17NGGC4PI5I0J',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Ball worked very well. Can at least handle the ...',
                content:
                    "Ball worked very well. Can at least handle the full body weight of a 250lb man. Fast shipping! Works as advertised. My ball was popped by my Dog after the first couple of days, I notified them, and they immediately offered a replacement ball, free of charge. I'm ready to get back into my workouts. This is great for me because I have a weak lower back. Helps take the pressure off of a large portion of my ab workouts.",
                stars: 5,
                verified: true,
                reviewCreated: 1510012800000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R2ECOJZUEDTXA0',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Happy With Purchase',
                content:
                    'I received the exercise ball to take with me on vacation so I can keep up with my exercise routine. Although I have not inflated the ball yet, I can report that, when deflated, it is small enough to pack in an overnight bag. The fact that it comes with a pump will allow me to inflate it when I want to use it.',
                stars: 5,
                verified: false,
                reviewCreated: 1509840000000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R3N5P46R3VXYOI',
                childAsin: 'B01M3S7P22',
                authorId: '',
                title: 'Kitten blankets.',
                content: 'Bought these for new baby kittens.',
                stars: 5,
                verified: true,
                reviewCreated: 1509408000000,
                productImg: '51+gRXywflL',
                productTitle: 'Hudson Baby Sherpa Blanket with Satin Binding, Pink',
                watched: false,
                created: 1517430130000
            },
            {
                country: 'US',
                reviewId: 'R1FYZF8ANUDBRF',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Five Stars',
                content: 'Love it!',
                stars: 5,
                verified: true,
                reviewCreated: 1509321600000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R2W0XDWXD8FYZP',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'This is a great ball for all things pilates',
                content:
                    "This is a great ball for all things pilates, yoga and barre. I am able to take it with me to travel and still get a great workout. I like that I don't always need the pump to blow it up.",
                stars: 5,
                verified: true,
                reviewCreated: 1509321600000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R2QDE7ON1S6KB2',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'had several sharp raised plastic areas on the circular thing ...',
                content:
                    "had several sharp raised plastic areas on the circular thing with the plastic balls inside. had to file it down so my infant son didn't get cut.",
                stars: 3,
                verified: true,
                reviewCreated: 1509235200000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1517430006000
            },
            {
                country: 'US',
                reviewId: 'R25NG2B26H28GI',
                childAsin: 'B014QK4G9A',
                authorId: '',
                title: 'Nice equipment to add in your daily exercise.',
                content: "Perfect size! Delivered on time. I'm now using it even I go travelling around.",
                stars: 5,
                verified: false,
                reviewCreated: 1509062400000,
                productImg: '611s34Lic7L',
                productTitle: 'Mini Exercise Ball for yoga, pilates, barre, fitness-Stability ball accessories ',
                watched: false,
                created: 1517345047000
            },
            {
                country: 'US',
                reviewId: 'RZSKVIUQF1MBH',
                childAsin: 'B014QK4G9A',
                authorId: '',
                title: 'It comes with a straw pump and e-manual.',
                content:
                    'It comes with straw which allowed me to inflate it in seconds. Before I receive it, i can first got an email from their customer service which is attached with an e-manual about how to exercise with this ball and which part of your body can be toned by different workout pose. It is helpful and you could also search on the internet for more exercise. Recommend!',
                stars: 5,
                verified: false,
                reviewCreated: 1508889600000,
                productImg: '611s34Lic7L',
                productTitle: 'Mini Exercise Ball for yoga, pilates, barre, fitness-Stability ball accessories ',
                watched: false,
                created: 1517345047000
            },
            {
                country: 'US',
                reviewId: 'R3VXLUWRZ8QBNF',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Great for physical therapy',
                content: 'Use it all the time for physical therapy exercises at home.',
                stars: 5,
                verified: true,
                reviewCreated: 1508630400000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389316000
            },
            {
                country: 'US',
                reviewId: 'R1IEH3BW6GLL8V',
                childAsin: 'B014QK4G9A',
                authorId: '',
                title: 'Clear instruction, great service!',
                content:
                    'The instruction I received is very clear and I follow it in my practice. Service is good as well!',
                stars: 5,
                verified: false,
                reviewCreated: 1508544000000,
                productImg: '611s34Lic7L',
                productTitle: 'Mini Exercise Ball for yoga, pilates, barre, fitness-Stability ball accessories ',
                watched: false,
                created: 1517345047000
            },
            {
                country: 'US',
                reviewId: 'R1XG51O3771R5M',
                childAsin: 'B014QK4G9A',
                authorId: '',
                title: 'No leak problem and once inflate, you could use it for very long time.',
                content:
                    "I've tried several barre ball before and most of them have the problem of leak. However, the HolaHatha ball is quite good and I have been using it for several months and didn't find any leak problem.",
                stars: 5,
                verified: false,
                reviewCreated: 1508544000000,
                productImg: '611s34Lic7L',
                productTitle: 'Mini Exercise Ball for yoga, pilates, barre, fitness-Stability ball accessories ',
                watched: false,
                created: 1517345047000
            },
            {
                country: 'US',
                reviewId: 'ROWWY7HHEOIRG',
                childAsin: 'B01FOREDY2',
                authorId: '',
                title: 'Five Stars',
                content: "Great product. I use it with my DVD's and it has held up well.",
                stars: 5,
                verified: true,
                reviewCreated: 1508544000000,
                productImg: '71b79%2B9NN%2BL',
                productTitle: 'Mini Exercise Ball with Pump - 9 Inch Bender Ball for Stability, Barre, Pilates,',
                watched: false,
                created: 1517389333000
            },
            {
                country: 'US',
                reviewId: 'RX6JXNSIGNXPG',
                childAsin: 'B014QK4G9A',
                authorId: '',
                title: 'Easy to blow up.',
                content:
                    'Use the clean straw the seller sent to me, it only cost me three breathe to inflate it. Super fast and convenient, no need for any pump.',
                stars: 5,
                verified: false,
                reviewCreated: 1508544000000,
                productImg: '611s34Lic7L',
                productTitle: 'Mini Exercise Ball for yoga, pilates, barre, fitness-Stability ball accessories ',
                watched: false,
                created: 1517345047000
            },
            {
                country: 'US',
                reviewId: 'R1PR5IHIU6EPAF',
                childAsin: 'B014QK4G9A',
                authorId: '',
                title: "The material is good and didn't expect any problem so far.",
                content:
                    'I used the barre ball on the wood floor and it served well.The surface is smooth and clean. Love it.',
                stars: 5,
                verified: false,
                reviewCreated: 1508457600000,
                productImg: '611s34Lic7L',
                productTitle: 'Mini Exercise Ball for yoga, pilates, barre, fitness-Stability ball accessories ',
                watched: false,
                created: 1517345047000
            },
            {
                country: 'US',
                reviewId: 'R26RRKKBKCBTYZ',
                childAsin: 'B014QK4G9A',
                authorId: '',
                title: 'Love the color, suitable for me.',
                content: 'The color is like the picture, love it. Pumps included, easy to inflate.',
                stars: 5,
                verified: false,
                reviewCreated: 1508457600000,
                productImg: '611s34Lic7L',
                productTitle: 'Mini Exercise Ball for yoga, pilates, barre, fitness-Stability ball accessories ',
                watched: false,
                created: 1517345047000
            },
            {
                country: 'US',
                reviewId: 'R1BQUF1D752DZD',
                childAsin: 'B014QK4G9A',
                authorId: '',
                title: 'Very good products',
                content: "It's perfect size and has been very durable with a lot of use.",
                stars: 5,
                verified: false,
                reviewCreated: 1508371200000,
                productImg: '611s34Lic7L',
                productTitle: 'Mini Exercise Ball for yoga, pilates, barre, fitness-Stability ball accessories ',
                watched: false,
                created: 1517345047000
            },
            {
                country: 'US',
                reviewId: 'R1DF62OVC0Z1C2',
                childAsin: 'B014QK4G9A',
                authorId: '',
                title: 'Sturdy ball',
                content: 'Looks strong and long-term using. I like it.',
                stars: 5,
                verified: false,
                reviewCreated: 1508371200000,
                productImg: '611s34Lic7L',
                productTitle: 'Mini Exercise Ball for yoga, pilates, barre, fitness-Stability ball accessories ',
                watched: false,
                created: 1517345047000
            },
            {
                country: 'US',
                reviewId: 'R1XJJUMMZEVNI0',
                childAsin: 'B014QK4G9A',
                authorId: '',
                title: "I have been using the yoga ball now for a few days. It's a great exercise ball",
                content: "I have been using the yoga ball now for a few days. It's a great exercise ball",
                stars: 5,
                verified: false,
                reviewCreated: 1508371200000,
                productImg: '611s34Lic7L',
                productTitle: 'Mini Exercise Ball for yoga, pilates, barre, fitness-Stability ball accessories ',
                watched: false,
                created: 1517345047000
            },
            {
                country: 'US',
                reviewId: 'RUPZ8MH4S9NNT',
                childAsin: 'B01353CVBO',
                authorId: '',
                title: 'Cute Elephant',
                content:
                    "I bought this (among other items) for a baby shower. This rattle is adorable! It's a little bigger than I expected, but I think that's a plus.",
                stars: 5,
                verified: true,
                reviewCreated: 1508371200000,
                productImg: '61YqZpvCyaL',
                productTitle: 'Bearington Baby Lil\' Spout Plush Elephant Shaker Rattle, 5"',
                watched: false,
                created: 1517430006000
            }
        ],
        hasMore: false
    }
];
